name: Build

on:
    workflow_call:
        inputs:
            app:
                required: true
                type: string
                description: Choice of Application A, B or C

jobs:
    build:
        runs-on: ubuntu-latest
        env:
          APP_A_PATH: "./react-app"
          APP_B_PATH: "./pypython"
          APP_C_PATH: "./java-maven"

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
  
            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'
              if: ${{ inputs.app == 'A' }}

            - name: Setup Python environment
              uses: actions/setup-python@v3
              with:
                python-version: '3.10'
              if: ${{ inputs.app == 'B' }}

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                java-version: '17'
                distribution: 'temurin'
                cache: maven
              if: ${{ inputs.app == 'C' }}

            - name: Installing Dependencies for ${{ inputs.app }}
              run: |
                echo " Installing Dependencies for ${{ inputs.app }}"
                if [[ "${{ inputs.app }}" == "A" ]]; then
                 echo "Installing Dependencies for  App A"
                 export APP_PATH=${{ env.APP_A_PATH }}
                 cd ./react-app
                 npm ci
                elif [[ "${{ inputs.app }}" == "B" ]]; then
                 echo "Installing Dependencies for  App B"
                 export APP_PATH=${{ env.APP_B_PATH }}
                 python -m pip install --upgrade pip
                 pip install flake8 pytest
                 if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                elif [[ "${{ inputs.app }}" == "C" ]]; then
                 echo "Install and Build for Java Meven for App C"
                 export APP_PATH=${{ env.APP_C_PATH }}
                 cd ./java-maven
                 mvn -B package --file pom.xml
                fi
            - name: Test ${{ inputs.app }}
              run: |
                echo " Test ${{ inputs.app }}"
                if [[ "${{ inputs.app }}" == "A" ]]; then
                 echo "Test App A"
                 cd ./react-app
                 npm test
                elif [[ "${{ inputs.app }}" == "B" ]]; then
                 echo "Test App B"
                 pwd
                 cd ./pyproject/src
                 pwd
                 python -m pytest addition.py
                 echo "Testing competed"
                elif [[ "${{ inputs.app }}" == "C" ]]; then
                 pwd
                 echo "Testing completed"
                fi
            - name: Lint for ${{ inputs.app }}
              run: |
                echo "Linting ${{ inputs.app }}"
                if [[ "${{ inputs.app }}" == "A" ]]; then
                 echo "Lint App A"
                 cd ./react-app
                 npm run lint
                elif [[ "${{ inputs.app }}" == "B" ]]; then
                 echo "Lint App B"
                 # stop the build if there are Python syntax errors or undefined names
                 flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                 # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
                 flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
                elif [[ "${{ inputs.app }}" == "C" ]]; then
                 pwd
                 echo "Lint App C"
                 echo "Lining for Java Meven completed"
                fi             