name: CI Pipeline

on:
    workflow_dispatch:
        inputs:
            app:
              description:  "The Application choices A, B or C"
              required: true
              default: "A"
              
jobs:
    trigger-reusable:     
        uses: ./.github/workflows/build-reusable.yml
        with: 
            app: ${{ inputs.app }}


