name: CI Pipeline

on:
    workflow_dispatch:
        inputs:
            app:
              type: choice
              description:  "Select the Application"
              options:
                - React-JS
                - Python
                - Java-Maven
              default: React-JS
              required: true
              
jobs:
    build-job:     
        uses: ./.github/workflows/build-reusable.yml
        with: 
            app: ${{ inputs.app }}

    sonarqube-job:  
        needs: build-job
        uses: ./.github/workflows/sonar-sast-reusable.yml
        with: 
            app: ${{ inputs.app }}

    jfrog-artifactory-job:  
        needs: sonarqube-job
        uses: ./.github/workflows/jfrog-artifactory-reusable.yml
        with: 
            app: ${{ inputs.app }}

    docker-job:  
        needs: jfrog-artifactory-job
        uses: ./.github/workflows/docker-image-reusable.yml
        with: 
            app: ${{ inputs.app }}
        
