name: CI Pipeline

on:
    workflow_dispatch:
        inputs:
            app:
              description:  "The Application choices A, B or C"
              required: true
              default: "A"
              
jobs:
    build-job:     
        uses: ./.github/workflows/build-reusable.yml
        with: 
            app: ${{ inputs.app }}

    sonarqube-job:  
        needs: build-job
        uses: ./.github/workflows/sonar-sast-reusable.yml
        with: 
            app: ${{ inputs.app }}

    jfrog-artifactory-job:  
        needs: build-job
        uses: ./.github/workflows/docker-image-reusable.yml
        with: 
            app: ${{ inputs.app }}

    docker-job:  
        needs: build-job
        uses: ./.github/workflows/docker-image-reusable.yml
        with: 
            app: ${{ inputs.app }}
        
