name: Jfrog Artifactory

on:
    workflow_call:
        inputs:
            app:
                required: true
                type: string
                description: The Application choices React-JS, Python or Java-Maven

jobs:
    jfrog-artifactory:
        name: Artifactory to Jfrog
        runs-on: ubuntu-latest
        steps:
            - name: Artifactory to Jfrog
              run: |
                echo " Artifacatory are stored in Jfrog Successfully"
