name: Jfrog Artifactory

on:
    workflow_call:
        inputs:
            app:
                type: string
                description: "Select the Application"
                required: true

jobs:
    jfrog-artifactory:
        name: Artifactory to Jfrog
        runs-on: ubuntu-latest
        steps:
            - name: Artifactory to Jfrog
              run: |
                echo " Artifacatory are stored in Jfrog Successfully"
